// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv28O0T8oeKJBt1RalzLwVMLm4fke-qhU',
    appId: '1:626764265701:web:4e6db10c2f796bbb353c0c',
    messagingSenderId: '626764265701',
    projectId: 'todoapp-81d02',
    authDomain: 'todoapp-81d02.firebaseapp.com',
    storageBucket: 'todoapp-81d02.firebasestorage.app',
    measurementId: 'G-RG9NQLY37V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-FtJ-URwWPn81xC3M21OYpHv2GILhgNs',
    appId: '1:626764265701:android:218f13664c126b5e353c0c',
    messagingSenderId: '626764265701',
    projectId: 'todoapp-81d02',
    storageBucket: 'todoapp-81d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwK59rETpFtpJzsNG3Q8W9Xt14P1BjNU',
    appId: '1:626764265701:ios:6591ca1332785ea0353c0c',
    messagingSenderId: '626764265701',
    projectId: 'todoapp-81d02',
    storageBucket: 'todoapp-81d02.firebasestorage.app',
    iosClientId: '626764265701-eiknguem683dkd7ccj67qluc271lh943.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwK59rETpFtpJzsNG3Q8W9Xt14P1BjNU',
    appId: '1:626764265701:ios:6591ca1332785ea0353c0c',
    messagingSenderId: '626764265701',
    projectId: 'todoapp-81d02',
    storageBucket: 'todoapp-81d02.firebasestorage.app',
    iosClientId: '626764265701-eiknguem683dkd7ccj67qluc271lh943.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
